### ISSUE TITLE
Date not recognised

### ISSUE THREAD

**Issue by hostops** [Hafinator/LazyFURS#2]
```
Unhandled exception. System.FormatException: String '15/06/2022 15:53:32' was not recognized as a valid DateTime.
   at LazyFURS.Program.ReadClosedPosition(ExcelPackage package) in C:\Users\Maks\Repos\LazyFURS\LazyFURS\Program.cs:line 688
   at LazyFURS.Program.Main() in C:\Users\Maks\Repos\LazyFURS\LazyFURS\Program.cs:line 80
   at LazyFURS.Program.<Main>()
Aborted (core dumped)
```

**Comment by Hafinator** [comment]
Can you give me the version?

**Comment by hostops** [comment]
v1.3.1
It may help you to know that I use etoro in english.

**Comment by Hafinator** [comment]
Same here

**Comment by Hafinator** [comment]
@hostops Can you tell me the language you're using? (en-US, de-DE, etc...)

**Comment by hostops** [comment]
en-US

**Comment by Hafinator** [comment]
Interesting. I have the same language settings and the same eToro language. I'll try to fix this using 'InvariantCulture'

**Comment by Hafinator** [comment]
And 'en-US' is your OS language correct? (just so we're clear) @hostops

**Comment by hostops** [comment]
Yes. I also use Linux (NixOs), kernel 5.15.94 with .NET Runtime 6.0.11.
I was able to run the program.
All dates in my account statement are in this format: DD/MM/YYYY hh:mm:ss (15/06/2022 15:53:32, 15/06/2022 16:05:55)

**Comment by Hafinator** [comment]
@hostops  Can you please check if the new latest build works for you?

**Comment by hostops** [comment]
Zal se vedno dobim tole. 

```
Unhandled exception. System.FormatException: String '15/06/2022 15:53:32' was not recognized as a valid DateTime.
   at LazyFURS.Program.ReadClosedPosition(ExcelPackage package) in C:\Users\Maks\Repos\LazyFURS\LazyFURS\Program.cs:line 689
   at LazyFURS.Program.Main() in C:\Users\Maks\Repos\LazyFURS\LazyFURS\Program.cs:line 80
   at LazyFURS.Program.<Main>()
Aborted (core dumped)
```

Ampak zame se ne mudi, saj sem za letos ze oddal davcne napovedi z uporabo https://github.com/masbug/etoro-edavki

Za drugo leto pa upam, da s skupnimi močmi (etoro-edavki + lazyFurs + lahko stejete se mene zraven) naredimo neko uporabniku prijazno spletno storitev, ki ga bo vodila cez cel postopek in se bi pretvorba naredila v browserju (ce se da offline) - da bodo lahko tudi neprogramerji oddajali svoje napovedi.

Aha pa vidim, da sem vmes zamenjal jezik.

**Comment by Hafinator** [comment]
Did you try updating the .NET 6 runtime to the latest one? (I'm kinda doubtful but, I'd like to dismiss this one)

**Comment by hostops** [comment]
Same result.

**Comment by Hafinator** [comment]
Hey @hostops I now changed the culture info to fr-FR as was suggested by @anejchy
Could you please check if this now works on Linux?
And thank you for bearing with me. :) (and sorry for the hassle I put you trough)

**Comment by hostops** [comment]
Sorry for late response. Yes now it is working.
Thanks.
