### ISSUE TITLE
Problemi

### ISSUE THREAD

**Issue by anejchy** [Hafinator/LazyFURS#3]
InvariantCulture za datume na ENG Windosih ne dela, sprememba na fr-FR dela:
![image](https://user-images.githubusercontent.com/29634004/221044726-1dc413f9-1cfd-457f-b4d2-cadc29460edc.png)

Problem v for zanki line 342 (sprememba iz "i" na "j" deluje):
![image](https://user-images.githubusercontent.com/29634004/221044111-d5bdf51d-1f9a-45ba-8aa5-1a684eff6866.png)

Enak problem:
![image](https://user-images.githubusercontent.com/29634004/221044374-ffafedfb-1224-4f55-8a80-bfee393974d2.png)

**Comment by Hafinator** [comment]
@anejchy najlepša hvala za tole, sploh pa hvala ker si mi posredoval rešitve (tistole z iteratorji 'i' in 'j' sem že enkrat popravu in kot  zgleda, po nesreči revertov)
